font_family      monospace
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 13.0

cursor_shape block
cursor_shape_unfocused hollow
cursor_beam_thickness 13
cursor_underline_thickness 2.0
cursor_blink_interval -1

scrollback_lines 20000
scrollbar scrolled
scrollbar_interactive yes
scrollbar_jump_on_click yes
scrollbar_width 0.25
scrollbar_hover_width 1
scrollbar_handle_opacity 0.5
scrollbar_radius 0.1
scrollbar_gap 0
scrollbar_hitbox_expansion 0.25
scrollbar_track_hover_opacity 0.1
scrollbar_handle_color foreground
scrollbar_track_color foreground

progress_bar top

mouse_hide_wait 3.0

url_color #0087bd
url_style dashed

open_url_with default
detect_urls yes

sync_to_monitor yes

enable_audio_bell yes


hide_window_decorations yes

confirm_os_window_close -1


background_opacity 1.0

background_blur 0

transparent_background_colors

remember_window_size  no
initial_window_width  640
initial_window_height 640

#:     # unmap a keyboard shortcut, passing it to the program running in kitty
#:     map kitty_mod+space
#:     # completely ignore a keyboard event
#:     map ctrl+alt+f1 discard_event
#:     # combine multiple actions
#:     map kitty_mod+e combine : new_window : next_layout
#:     # multi-key shortcuts
#:     map ctrl+x>ctrl+y>z action


#: normal colors
color0   #2e2e2e
color1   #eb4129
color2   #abe047
color3   #f6c744
color4   #47a0f3
color5   #7b5cb0
color6   #64dbed
color7   #e5e9f0

#: bright colors
color8   #565656
color9   #ec5357
color10  #c0e17d
color11  #f9da6a
color12  #49a4f8
color13  #a47de9
color14  #99faf2
color15  #ffffff

#: other colors
background            #000000
foreground            #ebdbb2   #: from gruvbox
cursor                #ebdbb2
#cursor                #eb64b2
cursor_text_color     #ebdbb2
selection_background  #eb64b2
selection_foreground  #ebdbb2
