import = ["~/.config/alacritty/opacity.toml", 
	"~/.config/alacritty/theme.toml"]

[window.padding]
x = 6
y = 6

[window]
decorations = "None"

[env]
TERM = "xterm-256color"

[font]
size = 12.0


[keyboard]
bindings = [
{ key = "a", mods = "Shift|Alt", action = "ToggleFullScreen" },
{ key = "u", mods = "Shift|Alt", command = "/home/me/.config/scripts/alacop100.sh"},
{ key = "i", mods = "Shift|Alt", command = "/home/me/.config/scripts/alacop75.sh"},
{ key = "o", mods = "Shift|Alt", command = "/home/me/.config/scripts/alacop0.sh"},
{ key = "d", mods = "Shift|Alt", command = "/home/me/.config/scripts/themed.sh"},
{ key = "s", mods = "Shift|Alt", command = "/home/me/.config/scripts/themel.sh"},
]

[font.bold]
family = "hack"
style = "Bold"

[font.bold_italic]
family = "hack"
style = "Bold Italic"

[font.italic]
family = "hack"
style = "Italic"

[font.normal]
family = "hack"
style = "Regular"
